### ISSUE TITLE
[TMap] 在 StrictMode 下，地图组件渲染有问题

### ISSUE THREAD

**Issue by ChenKuan1110** [Tencent/tlbs-map-react#1]
### tlbs-map-react 版本

1.0.0

### 重现链接

https://codesandbox.io/p/sandbox/mystifying-night-68649p

### 重现步骤

使用 StrictMode 的 ，地图组件 呈现如下：
![image](https://github.com/user-attachments/assets/cf3affc9-0022-4e00-b7df-0e9cc49c2f60)

取消 StrictMode ，正常
![image](https://github.com/user-attachments/assets/8d5c8d42-57d6-4c4c-bb58-7212325637cb)

如果使用布局强制修改 Map 容器的样式（比如通过修改 overflow: hiden），那么标记点不会程序

### 期望结果

有没有什么好的办法能够解决该问题 🙏

### 框架版本

18.2.0

**Comment by egbertshendong** [comment]
在StrictMode组件下地图组件会重复渲染，新发布了1.0.1版本解决了此问题，可以安装使用一下
