### ISSUE TITLE
[TMap] 地图组件上方存在一个透明覆盖层，导致在其上方显示的任何组件均无法操作

### ISSUE THREAD

**Issue by ZQDesigned** [Tencent/tlbs-map-react#2]
### tlbs-map-react 版本

1.0.1

### 重现链接

https://github.com/ZQDesigned/tlbs-bug

### 重现步骤

使用提供的仓库中的代码，无需任何额外步骤即可复现。

### 实际结果

地图组件上方存在的透明蒙层组件不应该影响在其上方创建的其他 React 组件，但是这个透明蒙层会拦截所有在地图组件位置上方的点击行为，不论点击位置的地图组件区域是否是可见状态。

https://github.com/user-attachments/assets/70279490-ce22-4e93-a23b-eaebff802a61

**Comment by ZQDesigned** [comment]
@egbertshendong 请问这个问题是否有解决方案呢

**Comment by egbertshendong** [comment]
地图引擎zIndex层级时1000，把代码中的Drawer组件设置zIndex是1001，即可解决 @ZQDesigned
<img width="774" alt="image" src="https://github.com/user-attachments/assets/3bfd277f-2abc-47ac-b30c-3686621116ab">

**Comment by egbertshendong** [comment]
> @egbertshendong 请问这个问题是否有解决方案呢
地图引擎zIndex层级s是1000，把代码中的Drawer组件设置zIndex是1001，即可解决
<img width="674" alt="image" src="https://github.com/user-attachments/assets/e06c1af8-5db9-4a81-a56c-2d5a04ccd869">

**Comment by ZQDesigned** [comment]
我尝试过设置drawer的zindex为1001，但是这没有解决问题。


------------------ 原始邮件 ------------------
发件人: egbertshendong ***@***.***&gt;
发送时间: 2024年11月20日 14:06
收件人: Tencent/tlbs-map-react ***@***.***&gt;
抄送: ZQDesigned ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [Tencent/tlbs-map-react] [TMap] 地图组件上方存在一个透明覆盖层，导致在其上方显示的任何组件均无法操作 (Issue #2)

**Comment by egbertshendong** [comment]
> 我尝试过设置drawer的zindex为1001，但是这没有解决问题。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: egbertshendong ***@***.***&gt; 发送时间: 2024年11月20日 14:06 收件人: Tencent/tlbs-map-react ***@***.***&gt; 抄送: ZQDesigned ***@***.***&gt;, Mention ***@***.***&gt; 主题: Re: [Tencent/tlbs-map-react] [TMap] 地图组件上方存在一个透明覆盖层，导致在其上方显示的任何组件均无法操作 (Issue #2)

我这里设置后是好了的，你再试一下

**Comment by ZQDesigned** [comment]
问题确实解决了，可能是之前开发环境代码没有自动 build 导致出现了未解决的假象。非常感谢！
