### ISSUE TITLE
无法使用原生api中的tools

### ISSUE THREAD

**Issue by ZRong-H** [Tencent/tlbs-map-react#3]
### tlbs-map-react 版本

1.0.1

### 补充说明

我需要使用原生的tools以进行多边形的绘制，然而当我创建了map的实例之后，无法直接通过ref绑定的实例获取到对应的tools内容。同时，也无法直接获取到GeometryEditor。我需要怎么做？
我想要实现与这个demo类似的功能：https://lbs.qq.com/webDemoCenter/glAPI/glEditor/toolDraw

**Comment by egbertshendong** [comment]
组件库没有提供多边形绘制和编辑组件，当前建议不使用组件库组件，参照demo直接调用api形式实现功能，我们后面计划增加多边形绘制和编辑组件 @ZRong-H

**Comment by ZRong-H** [comment]
> 组件库没有提供多边形绘制和编辑组件，当前建议不使用组件库组件，参照demo直接调用api形式实现功能，我们后面计划增加多边形绘制和编辑组件 @ZRong-H

我有意愿参与进这个开源项目。这个组件可以由我尝试去实现吗？

**Comment by egbertshendong** [comment]
> > 组件库没有提供多边形绘制和编辑组件，可以先参照demo直接调用api形式实现功能，我们后面计划增加多边形绘制和编辑组件 @ZRong-H
> 
> 我有意愿参与进这个开源项目。这个组件可以由我尝试去实现吗？

@ZRong-H 可以参与开源共建哈，我们开源的vue组件库有图形编辑器组件https://mapapi.qq.com/web/tlbs-map-vue/components/geometry-editor.html，可以参考功能实现react版本
