### ISSUE TITLE
[组件名称] 地图鉴权Key接口在域名下会存在跨域问题，需要多次代理

### ISSUE THREAD

**Issue by lanpang-zi** [Tencent/tlbs-map-react#4]
### tlbs-map-react 版本

1.0.1

### 重现步骤

地图鉴权Key接口在我司测试环境域名下会存在跨域问题，需要多次代理，怎么解决跨域问题
![微信截图_20241118123641](https://github.com/user-attachments/assets/31904530-b96c-40c8-8682-bbf2e247122f)

### 期望结果

不使用多次代理的情况下，不存在跨域

### 实际结果

出现跨域

**Comment by egbertshendong** [comment]
地图鉴权请求正常情况是一个jsonp请求应该不存在跨域问题，可以看一下项目中是否有劫持逻辑改变了鉴权请求 @lanpang-zi
